#!/bin/sh
#
#Copyright (c) 2013 Qualcomm Technologies, Inc.  All Rights Reserved.
#Qualcomm Technologies Proprietary and Confidential.

# Location launcher service  init.d script to start the Location Software's mcmlocserver daemon

set -e
wait_for_data_dir_mount() {
    while ! [ -d /data/misc ]
    do
        echo "waiting for /data to mount"
    done
}
wait_for_dev_dir_mount() {
    while ! [ -d /dev/socket ]
    do
        echo "waiting for /dev to mount"
    done
}

case "$1" in
  start)
        # create required directories for location services
        if [ ! -d /data/vendor/location/mq ]
        then
            wait_for_data_dir_mount
            mkdir -p /data/vendor/location/mq
        fi
        if [ ! -d /data/vendor/location/xtwifi ]
        then
            mkdir -p /data/vendor/location/xtwifi
        fi
        if [ ! -d /data/vendor/location/xtra ]
        then
            mkdir -p /data/vendor/location/xtra
        fi
        if [ ! -d /dev/socket/location/mq ]
        then
            wait_for_dev_dir_mount
            mkdir -p /dev/socket/location/mq
        fi
        if [ ! -d /dev/socket/location/xtra ]
        then
            mkdir -p /dev/socket/location/xtra
        fi
        echo -n "Starting Location Launcher Services: "
        start-stop-daemon -S -b -a /usr/bin/loc_launcher
        echo "done"
        ;;
  stop)
        echo -n "Stopping Location launcher Services: "
        start-stop-daemon -K -n loc_launcher
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage loc_launcher { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
