# Copyright (c) 2017-2018 Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#

# This file is used to generate the autogenerated code and blueprint/makefiles for the hals in
# com.qualcomm.qti.uceservice@2.0 service

HIDL_ROOT_DIR="$QCPATH/ims-ship/rcs/interfaces/uceservice"
LIBHIDL_COMPONENT='-r android.hidl:system/libhidl/transport'

IMS_UCE_INTERFACE_LIB='com.qualcomm.qti.uceservice@2.0'

LOC="$QCPATH/ims-ship/rcs/interfaces/uceservice/2.0/default"

hidl-gen -Landroidbp -r com.qualcomm.qti.uceservice:$HIDL_ROOT_DIR $LIBHIDL_COMPONENT $IMS_UCE_INTERFACE_LIB