/*
 * Copyright (c) 2018-2019 Qualcomm Technologies, Inc.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 *
 */

#include "pa_qti_effect.h"

static const pa_qti_effect_uuid_t SL_IID_TRUMPET_ = {0x5e46f50b, 0xcc86, 0x4d6e, 0x9610, {0x54, 0x72, 0x76, 0x1d, 0xd0, 0xe2}};
static const pa_qti_effect_uuid_t * const SL_IID_TRUMPET = &SL_IID_TRUMPET_;
static const pa_qti_effect_uuid_t SL_IID_TRUMPET_UUID = {0xa52a402b, 0xe254, 0x4fb9, 0xab7a, {0x7c, 0xf5, 0x83, 0x44, 0xe3, 0xf3}};

/* enumerated parameter settings for trumpet effect for both set and get parameter */
typedef enum {
    TRUMPET_PARAM_ENABLE,
    TRUMPET_PARAM_PREGAIN,
    TRUMPET_PARAM_POSTGAIN,
    TRUMPET_PARAM_SYSTEMGAIN,
    TRUMPET_PARAM_MI_DV_LEVELER_STEERING,
    TRUMPET_PARAM_MI_DIALOG_ENHANCER,
    TRUMPET_PARAM_MI_SURROUND_COMPRESSOR,
    TRUMPET_PARAM_MI_IEQ_STEERING,
    TRUMPET_PARAM_DIALOG_AMOUNT,
    TRUMPET_PARAM_DIALOG_DUCKING,
    TRUMPET_PARAM_DIALOG_ENABLE,
    TRUMPET_PARAM_VOLUME_LEVELER_AMOUNT,
    TRUMPET_PARAM_VOLUME_LEVELER_IN_TARGET,
    TRUMPET_PARAM_VOLUME_LEVELER_OUT_TARGET,
    TRUMPET_PARAM_VOLUME_LEVELER_ENABLE,
    TRUMPET_PARAM_VOLUME_MODELER_CALIBRATION,
    TRUMPET_PARAM_VOLUME_MODELER_ENABLE,
    TRUMPET_PARAM_VOLMAX_BOOST,
    TRUMPET_PARAM_BASS_BOOST,
    TRUMPET_PARAM_BASS_CUTOFF_FREQ,
    TRUMPET_PARAM_BASS_WIDTH,
    TRUMPET_PARAM_BASS_ENABLE,
    TRUMPET_PARAM_BASS_EXTRACT_CUTOFF_FREQ,
    TRUMPET_PARAM_BASS_EXTRACT_ENABLE,
    TRUMPET_PARAM_REGULATOR_SET,
    TRUMPET_PARAM_REGULATOR_OVERDRIVE,
    TRUMPET_PARAM_REGULATOR_TIMBRE_PRESERVE,
    TRUMPET_PARAM_REGULATOR_RELAXATION_AMT,
    TRUMPET_PARAM_REGULATOR_SPKR_DIST_ENABLE,
    TRUMPET_PARAM_REGULATOR_ENABLE,
    TRUMPET_PARAM_VIRTUAL_BASS_MODE,
    TRUMPET_PARAM_VIRTUAL_BASS_SRC_FREQ,
    TRUMPET_PARAM_VIRTUAL_BASS_MIX_FREQ,
    TRUMPET_PARAM_VIRTUAL_BASS_OVERALL_GAIN,
    TRUMPET_PARAM_VIRTUAL_BASS_SUBGAINS,
    TRUMPET_PARAM_VIRTUAL_BASS_SLOPE_GAIN,
    TRUMPET_PARAM_FRONT_SPK_ANG,
    TRUMPET_PARAM_SURROUND_SPK_ANG,
    TRUMPET_PARAM_HEIGHT_SPK_ANG,
    TRUMPET_PARAM_HEIGHT_FILTER_MODE,
    TRUMPET_PARAM_SURROUND_BOOST,
    TRUMPET_PARAM_SURROUND_DECODER_ENABLE,
    TRUMPET_PARAM_CALIBRATION,
    TRUMPET_PARAM_GRAPHICS_ENABLE,
    TRUMPET_PARAM_GRAPHICS_SET,
    TRUMPET_PARAM_AUDIO_OPTIMIZER_ENABLE,
    TRUMPET_PARAM_AUDIO_OPTIMIZER_SET,
    TRUMPET_PARAM_PROCESS_OPTIMIZER_ENABLE,
    TRUMPET_PARAM_PROCESS_OPTIMIZER_SET,
    TRUMPET_PARAM_IEQ_ENABLE,
    TRUMPET_PARAM_IEQ_AMOUNT,
    TRUMPET_PARAM_IEQ_SET,
    TRUMPET_PARAM_OP_MODE,
    TRUMPET_PARAM_DYNAMIC_PARAMETER,
} pa_qti_trumpet_params_t;
