ifneq ($(BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE),)
ifneq ($(BOARD_VENDOR_QCOM_LOC_PDK_FEATURE_SET),true)
ifneq ($(TARGET_SUPPORTS_ANDROID_WEAR),true)

include $(call all-subdir-makefiles)

endif # TARGET_SUPPORTS_ANDROID_WEAR
endif # BOARD_VENDOR_QCOM_LOC_PDK_FEATURE_SET
endif # BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE
